
on:
  push:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Hi world
        id: hello
        uses: actions/demo-powershell-github-actions@v1     
      