
on:
  push:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Hi world
        shell: pwsh
        env:
          SERVICE_PRINCIPAL: "http://jackGitAct"
          TENANT_ID: ${{ secrets.TENANT_ID }}
          APPID: ${{ secrets.APP_ID }}
          SERVICE_PASS: ${{ secrets.SERVICE_PRINCIPAL_PASS}}
        run: ./action.yml
      