Name: "New workflow" 

on:
  push:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      -name: Hi world
      id: hello
      user: actions/demo-powershell-github-actions@v1     
      