Name: "New workflow" 

on:
  push:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      uses: "./.github/azdeploy"
      
      env:
        SERVICE_PRINCIPAL: "http://jackGitAct",
        TENANT_ID: ${{ secrets.TENANT_ID}},
        APPID: ${{ secrets.APP_ID }}
        SERVICE_PASS: $ {{ sectrets.SERVICE_PRINCIPAL_PASS}}
      